package com.microservice.SAPPostService.model;

import jakarta.persistence.*;
import lombok.Data;

/*
 * This is the model class for the posts table in the database.
 * It has the following fields:
 * - postId: the id of the post which will generated by the database
 * - authorId: author id a foreign key to the users table
 * - title: the title of the post
 * - content: the content of the post
*/
@Entity
@Data
@Table(name = "posts")
public class Post {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    @Column(name = "post_id")
    private Long postId;

    @Column(name = "author_id")
    private Long userId;

    @Column(name = "title")
    private String title;

    @Column(name = "content")
    private String content;
}