package com.microservice.SAPPostService.dto;

import lombok.Data;

/*
 * This is the DTO class for the posts table in the database.
 * It has the folowing fields:
 * These fields are for the response of the added posts
 * - postId: the id of the post which will generated by the database
 * - authorId: author id a foreign key to the users table
 * - title: the title of the post
 * - content: the content of the post
 */

@Data
public class PostResponse {
    private Long postId;

    private Long userId;

    private String title;

    private String content;
}